eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  mail:
    host: smtp.qq.com
    username: 1456088081@qq.com
    password: spgcdvxealnugdda
  application:
    name: mq-service
  rabbitmq:
    host: 106.52.52.92
    port: 5672
    username: qsyy2077
    password: qsyy7614
server:
  port: 8151